### ISSUE TITLE
Functions called by 'unitroot.m' are missing.

### ISSUE THREAD

**Issue by lnsongxf** [ambropo/VAR-Toolbox#1]
Hi Dr. Ambrogio Cesa-Bianchi,

I found that the functions called by `unitroot.m` are missing.
I believe they can be downloaded at [here](https://econpapers.repec.org/RAS/pka10.htm).

Thanks for your great work.

Mark Song

**Comment by ambropo** [comment]
Dear Mark, thanks for the message and for spotting this. I realised that unitroot.m was a duplicate. The VAR Toolbox uses the adf.m routine of the Le Sage Toolbox for unit root tests. I therefore deleted the file unitroot.m from the repository. Many thanks again
